"""Exporting an answer record.

The promise this keeps: *"export gives you prose plus a real .bib where every
entry resolves"*. That is only true because the record already passed the gate —
export does not verify anything, it renders what survived. Anything it emits was
checked before it was written.

Three formats, each for a different destination: Markdown to read, LaTeX with a
real BibTeX file to paste into a paper, and a Jupyter notebook that re-runs the
physics rather than describing it.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from .answer.records import AnswerRecord

#: Characters BibTeX will not accept in a citation key.
_KEY_RE = re.compile(r"[^A-Za-z0-9_:-]")


def _bib_key(paper_id: str) -> str:
    """A stable BibTeX key from a paper id."""
    return _KEY_RE.sub("", paper_id.replace("arXiv:", "arxiv"))


def to_markdown(record: AnswerRecord) -> str:
    """Render the record as Markdown, quotes inline."""
    from .answer.pipeline import render_markdown

    return render_markdown(record)


def to_bibtex(record: AnswerRecord, titles: dict[str, str] | None = None) -> str:
    """A BibTeX file covering every paper the answer actually cites.

    Only papers that appear in an accepted claim's anchors are included. An entry
    for a paper the answer did not end up using would be exactly the "cited but
    never read" pattern this project reports on elsewhere.
    """
    titles = titles or {}
    papers: dict[str, str] = {}
    for claim in record.claims:
        for anchor in claim.anchors:
            papers.setdefault(anchor["paper_id"], titles.get(anchor["paper_id"], ""))

    entries = []
    for paper_id, title in sorted(papers.items()):
        key = _bib_key(paper_id)
        eprint = paper_id.replace("arXiv:", "")
        entries.append(
            "\n".join(
                [
                    f"@article{{{key},",
                    f"  title        = {{{title or paper_id}}},",
                    f"  eprint       = {{{eprint}}},",
                    "  archivePrefix = {arXiv},",
                    f"  note         = {{verified by noether against corpus {record.corpus_hash[:12]}}},",
                    "}",
                ]
            )
        )
    return "\n\n".join(entries) + ("\n" if entries else "")


def to_latex(record: AnswerRecord, titles: dict[str, str] | None = None) -> str:
    """LaTeX prose with ``\\cite`` keys matching :func:`to_bibtex`."""
    lines = [
        "% Generated by noether. Every claim below was verified against a span",
        f"% in a real paper; corpus {record.corpus_hash[:12]}.",
        "",
    ]
    for claim in record.claims:
        keys = sorted({_bib_key(a["paper_id"]) for a in claim.anchors})
        citation = f"~\\cite{{{','.join(keys)}}}" if keys else ""
        lines.append(f"{_escape(claim.text)}{citation}")
        lines.append("")

    if record.equations:
        lines.append("% Equations, with the verdicts recorded at export time.")
        for equation in record.equations:
            lines.append(f"% dimensions: {equation.dimensions}"
                         + (f" -- {equation.detail}" if equation.detail else ""))
            for note in equation.notes:
                lines.append(f"% note: {note}")
            lines.append("\\begin{equation}")
            lines.append(f"  {equation.latex}")
            lines.append("\\end{equation}")
            lines.append("")

    if record.dropped:
        lines.append("% Dropped by the verification gate and NOT included above:")
        for item in record.dropped:
            subject = (item["claim"] or item["detail"])[:90]
            lines.append(f"%   [{item['reason']}] {subject}")

    return "\n".join(lines)


def _escape(text: str) -> str:
    """Escape the characters LaTeX would otherwise interpret."""
    for character, replacement in (
        ("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
        ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
    ):
        text = text.replace(character, replacement)
    return text


def to_notebook(record: AnswerRecord) -> str:
    """A Jupyter notebook that re-runs the answer's equations.

    A notebook that merely restates the prose would be a worse Markdown file.
    This one carries executable cells, so a reader can change a parameter and
    see what happens rather than taking the number on trust.
    """
    cells: list[dict] = [
        _markdown_cell([f"# {record.question}\n", f"\nCorpus `{record.corpus_hash[:12]}` · {record.summary()}\n"]),
    ]

    for index, claim in enumerate(record.claims, start=1):
        body = [f"**{index}.** {claim.text}\n"]
        for anchor in claim.anchors:
            body.append(f"\n> {anchor['quote'][:300]}\n")
            body.append(
                f"\n— `{anchor['paper_id']}`, {anchor['section_path'] or 'no section'}, "
                f"chars {anchor['start']}–{anchor['end']}\n"
            )
        cells.append(_markdown_cell(body))

    if record.equations:
        cells.append(_markdown_cell(["## Equations\n"]))
        cells.append(
            _code_cell(
                [
                    "from noether.compute.symbolic import parse_equation\n",
                    "from noether.compute.units import check_equation\n",
                    "from noether.compute.run import evaluate\n",
                ]
            )
        )
        for equation in record.equations:
            source = [
                f"latex = r\"\"\"{equation.latex}\"\"\"\n",
                "parsed = parse_equation(latex)\n",
                "check = check_equation(parsed)\n",
                "print(parsed.normalised)\n",
                "print(check)\n",
            ]
            if equation.notes:
                source.insert(0, "# " + "; ".join(equation.notes) + "\n")
            cells.append(_code_cell(source))

    if record.dropped:
        cells.append(
            _markdown_cell(
                ["## Dropped by the gate\n\n"]
                + [f"- `{d['reason']}` {(d['claim'] or d['detail'])[:110]}\n" for d in record.dropped]
            )
        )

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1)


def _markdown_cell(source: list[str]) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def _code_cell(source: list[str]) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}


def write(record: AnswerRecord, directory: Path, fmt: str, titles: dict[str, str] | None = None) -> list[Path]:
    """Write an export. Returns every file created."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    stem = record.answer_id
    written: list[Path] = []

    if fmt == "markdown":
        path = directory / f"{stem}.md"
        path.write_text(to_markdown(record), encoding="utf-8")
        written.append(path)
    elif fmt == "latex":
        tex = directory / f"{stem}.tex"
        tex.write_text(to_latex(record, titles), encoding="utf-8")
        bib = directory / f"{stem}.bib"
        bib.write_text(to_bibtex(record, titles), encoding="utf-8")
        written.extend([tex, bib])
    elif fmt == "jupyter":
        path = directory / f"{stem}.ipynb"
        path.write_text(to_notebook(record), encoding="utf-8")
        written.append(path)
    else:
        raise ValueError(f"unknown format {fmt!r}; use markdown, latex or jupyter")

    return written
